### ISSUE TITLE
CAPWebView not found

### ISSUE THREAD

**Issue by andypoptacular** [ionic-team/ionic-portals#111]
I’ve been trying to build the Portals iOS framework from source (due to issues using Cocoapods with my ObjC project) but have come across this…

In ‘PortalWebView.swift on line 64:
‘class InternalCapWebView: CAPWebView {‘

This line fails as ‘CAPWebView’ cannot be found and I cannot see anywhere this is defined (in Portals or Capacitor). Am I missing something? (e.g. a specific Capacitor version).

I assume it must be something I'm doing wrong as you must be able to build it there.  Any help would be greatly appreciated.

**Comment by carlpoole** [comment]
Hi there, I don't think you are doing anything wrong in this case. We currently build the iOS Capacitor dependency for Portals based on the `portals-dev` branch of Capacitor. If you are building from source try checking out that branch of Capacitor and see if it fixes your issue.

**Comment by andypoptacular** [comment]
Yep, that's it.  Thanks for your quick response.
