### ISSUE TITLE
Cocoapods Installation Error

### ISSUE THREAD

**Issue by tinahir** [ionic-team/ionic-portals#122]
[!] Error installing IonicLiveUpdates
[!] /usr/bin/git clone https://github.com/ionic-team/live-updates-sdk.git /var/folders/wp/yy92cy4j28q2m49vszqs4srm0000gn/T/d20220209-54213-1wln4g6 --template= --single-branch --depth 1

Cloning into '/var/folders/wp/yy92cy4j28q2m49vszqs4srm0000gn/T/d20220209-54213-1wln4g6'...
remote: Repository not found.
fatal: repository 'https://github.com/ionic-team/live-updates-sdk.git/' not found

**Comment by thomasvidas** [comment]
How are you trying to install IonicPortals? Currently the only supported installation methods are via MavenCentral and Cocoapods

**Comment by tinahir** [comment]
> How are you trying to install IonicPortals? Currently, the only supported installation methods are via MavenCentral and Cocoapods

I have Cocoapods. Pod install

**Comment by thomasvidas** [comment]
This is fixed in the recent 0.4.2 release
