### ISSUE TITLE
Missing cordova dependency in Android build

### ISSUE THREAD

**Issue by madshgk** [ionic-team/ionic-portals#143]
Im using this gradle dependency:     `implementation("io.ionic:portals:0.5.0")`

Gradle can compile build files but warns it missing dependecy to Cordova. I can however reference code from your lib.

When building app project, it fails, its complains about missing Cordova  dependency. 

```
> Could not resolve all files for configuration ':app:demoDebugRuntimeClasspath'.
   > Could not find org.apache.cordova:framework:7.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/cordova/framework/7.0.0/framework-7.0.0.pom
       - https://repo.maven.apache.org/maven2/org/apache/cordova/framework/7.0.0/framework-7.0.0.pom
       - https://maven.shortcut.io/org/apache/cordova/framework/7.0.0/framework-7.0.0.pom
     Required by:
         project :app > io.ionic:portals:0.5.0 > com.capacitorjs:core:3.4.1
```

Am i missing any other dependencies or?

**Comment by Steven0351** [comment]
`org.apache.corodova:framework:7.0.0` is in jcenter

**Comment by madshgk** [comment]
Yes, thank you. I added Jcenter to buildscript repo only :/
