### ISSUE TITLE
Unable to load web content

### ISSUE THREAD

**Issue by jrbj** [ionic-team/ionic-portals#150]
Following the QuickStart guides, it seems like in iOS the web content is expected to be a Capacitor app? The same built web app works for Android.

Here's the error in the Xcode console:

⚡️  ERROR: Unable to find application directory at: "file:///private/var/containers/Bundle/Application/6C3DFA39-02A0-4878-A78B-3C3D535AD9EE/PortalsDemo.app/public"!
Unable to find capacitor.config.json, make sure it exists and run npx cap copy.
Unable to find config.xml, make sure it exists and run npx cap copy.
2022-06-15 12:11:53.660581-0700 PortalsDemo[5584:383934] [ViewportSizing] maximumViewportInset cannot be larger than frame
2022-06-15 12:11:53.660622-0700 PortalsDemo[5584:383934] [ViewportSizing] minimumViewportInset cannot be larger than frame
⚡️  ERROR: Unable to load /private/var/containers/Bundle/Application/6C3DFA39-02A0-4878-A78B-3C3D535AD9EE/PortalsDemo.app/public
⚡️  This file is the root of your web app and must exist before
⚡️  Capacitor can run. Ensure you've run capacitor copy at least
⚡️  or, if embedding, that this directory exists as a resource directory.

**Comment by Steven0351** [comment]
Please provide steps to reproduce.

**Comment by jrbj** [comment]
Thanks! I have a repo here that has the issue. (Portals API key has been removed).
https://github.com/jrbj/PortalsDemo

The web app content at the root does work and successfully displays in Android.

Steps:
- Open the workspace
- Build and Run (Sim or device)
- App crashes with error (see issue description)
