### ISSUE TITLE
Portals for ionic Angular

### ISSUE THREAD

**Issue by vfmlucasguo** [ionic-team/ionic-portals#182]
Hi ionic team,

Our project is using ionic 3, cordova, Angular. I would like to know if we can use Portals, Our company is very interested in this feature: Micro Frontends with Module Federation, but did not find documentation and Demo for ionic Angular.

thanks!

**Comment by Steven0351** [comment]
@vfmlucasguo you can find more information regarding Portals for Capacitor at our [documentation site](https://ionic.io/docs/portals/for-capacitor/overview). Portals for Capacitor is a closed-source enterprise plugin, this repo is for the source available plugin used for native iOS, Android, and React Native projects.

**Comment by eric-horodyski** [comment]
@vfmlucasguo - You can find a demo application for Portals for Capacitor using Angular at the following link: https://github.com/ionic-team/cs-portals-capacitor-ng. 

Please note that you will need a trial key to run the application, which you can get [here](https://go.ionicframework.com/portals-for-capacitor).

**Comment by vfmlucasguo** [comment]
Hi @Steven0351 @eric-horodyski ,Thanks for your reply, I have successfully  run the project locally： [https://github.com/ionic-team/cs-portals-capacitor-ng](url)，but there were problems

1. When I run: npm run run:all，The shell wasn't running, so I need to run : nx run shell:serve -o
<img width="684" alt="image" src="https://user-images.githubusercontent.com/97436761/198218265-88ffe918-62fa-434f-9e86-215309e7e325.png">

2. When I want to build the Demo in ionic dashboard，I wonder if this supports live update，Can it be packaged with Android and iOS in ionic dashboard.
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/97436761/198226775-02fab543-f237-40f5-b359-edb36ab52199.png">

thanks !

**Comment by Steven0351** [comment]
@vfmlucasguo please open issues related to the demo on the demo project. Portals for Capacitor is a completely separate project and codebase from this repository.
