### ISSUE TITLE
Hybrid Routing Management"

### ISSUE THREAD

**Issue by lcy19** [ionic-team/ionic-portals#247]
Hi, I want to integrate ionic into native app and when I am in the page of ionic, I want to go to native again or to another h5 page, is there any way to do that?
Checked the sample of [ecommerce-app](https://ionic.io/docs/portals/for-ios/examples/ecommerce-app) and didn't find anything about it. Any suggestions or approaches? Thanks for your help!

**Comment by Steven0351** [comment]
That's going to be specific to your application and can't really give any suggestions as to specific implementation details. The simplest approach would be to use pub/sub to send a message to the native side to dismiss your web experience or to tell it to present a different experience. The vast majority of the code for what you're would be written in native.
