### ISSUE TITLE
bug: Call to objc_getClassList in CapacitorBridge causes crash if presenting Portals view based on Apple SDK availability

### ISSUE THREAD

**Issue by pbush25** [ionic-team/ionic-portals#255]
https://github.com/ionic-team/capacitor/issues/7116

Posting here for more visibility, as this is specifically related to Portal's itself.

**Comment by Steven0351** [comment]
This is a known issue. Latest versions of portals _require_ that you manually register plugins. If you're not using plugins, then you should set `pluginRegistrationStrategy` to `.manual([])` via initializer or directly.

https://ionic.io/docs/portals/for-ios/upgrade-guides#plugin-registration
