### ISSUE TITLE
blink red when back navigation

### ISSUE THREAD

**Issue by bdhwan** [ionic-team/ionic-portals#90]
<img width="524" alt="스크린샷 2021-10-22 오전 1 15 31" src="https://user-images.githubusercontent.com/5001286/138317109-c0214790-e464-4829-98ba-7819d76682da.png">
<img width="524" alt="스크린샷 2021-10-22 오전 1 15 45" src="https://user-images.githubusercontent.com/5001286/138317134-b16ab80a-bbc9-4a34-ab88-9c67fcec205c.png">
<img width="524" alt="스크린샷 2021-10-22 오전 1 15 52" src="https://user-images.githubusercontent.com/5001286/138317141-0d63297e-3e20-475b-82cc-f4c90e36f6ec.png">
<img width="524" alt="스크린샷 2021-10-22 오전 1 15 57" src="https://user-images.githubusercontent.com/5001286/138317147-dad78446-471e-4fea-9d71-17e9816aa6cc.png">

I add portalview in my fragment.
And go Other fragment.
And go Back. 
Always blink red light.
Only PortalView area hppened.

How can i fix it?

**Comment by carlpoole** [comment]
Hi there, I noticed you closed this issue. Was this still a problem for you?

**Comment by bdhwan** [comment]
yes. if there is better solution. i fixed it by download all portal code and change layout file.

**Comment by carlpoole** [comment]
We'll look at getting this fixed next release. It wasn't intended for there to be a red background on this view. Thank you for reporting it
